spring.application.name=festapp
# h2 config
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update

# key jwt ejemplo para probar la cadena
jwt.secret=K>lf.pnUOzmPFuvY*),X^B5!4Rj1d{0G27B
jwt.expiration=3600000